github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
    
#image: ghcr.io/pahud/gitpod-workspace:latest
image: ghcr.io/pahud/vscode:lates
#   file: .gitpod.Dockerfile


vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
